# Generated by Django 5.2.17 on 2026-09-04 08:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('meeting_date', models.DateField(db_index=True, verbose_name='会议日期')),
                ('raw_text', models.TextField(verbose_name='原始记录')),
                ('parse_status', models.CharField(choices=[('not_parsed', '未解析'), ('parsing', '解析中'), ('success', '解析成功'), ('failed', '解析失败'), ('imported', '已入库')], default='not_parsed', max_length=20, verbose_name='解析状态')),
                ('parse_error', models.TextField(blank=True, verbose_name='解析错误')),
                ('raw_llm_response', models.TextField(blank=True, verbose_name='模型原始响应')),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='姓名')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('paused', '暂停'), ('done', '已完成'), ('archived', '已归档')], default='not_started', max_length=24, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='总体进度')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='计划完成')),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='结构化草稿')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.meetingnote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='里程碑')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('delayed', '已延期')], default='not_started', max_length=24, verbose_name='状态')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='core.meetingnote')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
            options={
                'ordering': ['target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240, verbose_name='任务')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='截止日期')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='验收日期')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('acceptance', '待验收'), ('done', '已完成'), ('delayed', '已延期'), ('blocked', '阻塞')], db_index=True, default='not_started', max_length=24, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=16, verbose_name='优先级')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度')),
                ('current_note', models.TextField(blank=True, verbose_name='当前说明')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.project')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='core.meetingnote')),
            ],
            options={
                'ordering': ['due_date', '-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.CharField(choices=[('risk', '风险'), ('blocker', '阻塞'), ('decision', '待决策'), ('warning', '预警'), ('incident', '异常')], default='risk', max_length=16, verbose_name='类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('open', '待处理'), ('tracking', '跟进中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='open', max_length=16, verbose_name='状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to='core.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='core.project')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.meetingnote')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(blank=True, max_length=24)),
                ('completed_work', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('meeting_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to='core.meetingnote')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='core.task')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='core_task_project_3c46c4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='core_task_assigne_c4dd42_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='task_progress_percentage'),
        ),
    ]
