# Generated by Django 5.2.17 on 2026-09-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parse_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_for',
            field=models.DateField(blank=True, db_index=True, help_text='准备在哪天推进，与承诺的截止日期分开管理。', null=True, verbose_name='安排日期'),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='阶段名称')),
                ('description', models.TextField(blank=True, verbose_name='交付内容')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='显示顺序')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('delayed', '已延期')], default='not_started', max_length=24, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='计划开始')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划完成')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.project')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.projectphase', verbose_name='所属阶段'),
        ),
    ]
