# Generated by Django 5.2.17 on 2026-09-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdraft',
            name='review_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂存时间'),
        ),
        migrations.AddField(
            model_name='importdraft',
            name='review_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='审阅暂存'),
        ),
        migrations.AddField(
            model_name='importdraft',
            name='review_version',
            field=models.PositiveIntegerField(default=0, verbose_name='暂存版本'),
        ),
    ]
