# Generated by Django 5.2.17 on 2026-09-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_draft_review_stash'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='applied_to_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='occurred_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True)),
                ('meeting_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_session', to='core.meetingnote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
