from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("", views.dashboard, name="dashboard"),
    path("meetings/new/", views.meeting_create, name="meeting_create"),
    path("meetings/<int:pk>/", views.meeting_detail, name="meeting_detail"),
    path("meetings/<int:pk>/parse/", views.meeting_parse, name="meeting_parse"),
    path("drafts/<int:pk>/", views.draft_review, name="draft_review"),
    path("drafts/<int:pk>/confirm/", views.draft_confirm, name="draft_confirm"),
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/board/", views.task_board, name="task_board"),
    path("tasks/new/", views.task_edit, name="task_create"),
    path("tasks/<int:pk>/", views.task_detail, name="task_detail"),
    path("tasks/<int:pk>/progress/", views.task_progress_update, name="task_progress_update"),
    path("tasks/<int:pk>/edit/", views.task_edit, name="task_edit"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/new/", views.project_edit, name="project_create"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path("projects/<int:pk>/edit/", views.project_edit, name="project_edit"),
    path("people/", views.person_list, name="person_list"),
    path("people/new/", views.person_edit, name="person_create"),
    path("people/<int:pk>/", views.person_detail, name="person_detail"),
    path("people/<int:pk>/edit/", views.person_edit, name="person_edit"),
    path("reports/weekly/", views.report_view, name="report"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/export/json/", views.export_json, name="export_json"),
    path("settings/export/csv/", views.export_csv, name="export_csv"),
]
